### ISSUE TITLE
"'tpu driver': NOT FOUND" when running singularity w/ GPU

### ISSUE THREAD

**Issue by ggavelis** [nf-core/proteinfold#284]
### Description of the bug

Hello,

I'm trying to run proteinfold (in alphafold2 mode) via singularity in my center's computing cluster, which has a GPU node (an NVIDIA A100 GPU). The issue arises at the alphafold2 step, when tensorflow is unable to find a 'libcuda.so.1' file necessary to work with nvidia's GPU.

I was thankful/hopeful for your recent bugfix yesterday (https://github.com/nf-core/proteinfold/issues/281), but alas I still have the error, which is unchanged:

THE ERROR

> I0402 11:29:43.730433 22362487703360 templates.py:857] Using precomputed obsolete pdbs ./pdb_mmcif/obsolete.dat.
> I0402 11:29:43.913350 22362487703360 xla_bridge.py:353] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
> 2025-04-02 11:29:43.915963: W external/org_tensorflow/tensorflow/tsl/platform/default/dso_loader.cc:66] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /conda/lib:/usr/local/cuda-11.4/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs
> 2025-04-02 11:29:43.916000: W external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
> I0402 11:29:43.916183 22362487703360 xla_bridge.py:353] Unable to initialize backend 'cuda': FAILED_PRECONDITION: No visible GPU devices.
> I0402 11:29:43.916271 22362487703360 xla_bridge.py:353] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: Interpreter CUDA Host
> I0402 11:29:43.916584 22362487703360 xla_bridge.py:353] Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_temp/dbs/proteinfold/work/be/4b6dc5448f8161a1578704f0dd1859/.command.err

MY COMMAND

```
module load singularity/3.8.0
module load nextflow/24.10.5

nextflow run nf-core/proteinfold \
    --input samplesheet.csv \
    --outdir test_output \
    --mode alphafold2 \
    --full_dbs false \
    --alphafold2_model_preset monomer \
    --use_gpu true \
    -profile charlie   # Name of my profile in the config file
```

CONTENTS OF MY nextflow.config file
```
profiles {
    charlie {
        process {
            executor = 'pbspro'
            queueSize = 100000
            module = 'singularity/3.8.0'
            queue = 'gpu'
            errorStrategy = {task.attempt <= 3 ? 'retry' : 'ignore'}
            memory = {1.GB * task.attempt}
            cpus = {1 * task.attempt}
            maxRetries = 3
            clusterOptions = '-W umask=0002 -koed -o /dev/null -e /dev/null'
        }
        singularity {
            sandbox = true
            if (params.use_gpu) { singularity.runOptions = '--nv' }
            enabled = true
            autoMounts = true
            runOptions = '--bind /mnt'
            cacheDir = '/mnt/scgc_nfs/containers/'
            pullTimeout = '200 min'
        }
    }
}
```

Thanks for all your great tools! I really appreciate ya'll good folks at the nf-core.

~Greg

### Command used and terminal output

```console

```

**Comment by JoseEspinosa** [comment]
Thanks!
The fix you mentioned it is actually on the `dev` branch of the pipeline. If the command you used is the one above, I'd say you are running the last released version. Could you try to add to your command `-r dev`? Otherwise, you can also set the development image, adding it to the `process` scope of your config and see whether the issue is fixed. Please let me know if this fixes the issue 😄 
```
process {
    withName: RUN_ALPHAFOLD2 {
        container = "nf-core/proteinfold_alphafold2_standard:dev"
...
}
```

**Comment by ggavelis** [comment]
Hi Jose, Sorry for the late response.

**Approach A.**
If I add "-r dev" to the "nextflow -run" command above,  it runs the pipeline to completion, but weirdly skips the alphafold step. (See tower screenshot below)

![Image](https://github.com/user-attachments/assets/ee64e92e-2c8f-4bb5-ac02-fac67a9a7336)

**Approach B.**
Alternately, if I add the process block you mentioned to my nextflow.config file, it will attempt alphafold, and alphafold will throw this error message:

`I0402 11:20:17.572451 22423334270784 templates.py:857] Using precomputed obsolete pdbs ./pdb_mmcif/obsolete.dat.
I0402 11:20:17.757784 22423334270784 xla_bridge.py:353] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
2025-04-02 11:20:17.760522: W external/org_tensorflow/tensorflow/tsl/platform/default/dso_loader.cc:66] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /conda/lib:/usr/local/cuda-11.4/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs
2025-04-02 11:20:17.760561: W external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
I0402 11:20:17.760743 22423334270784 xla_bridge.py:353] Unable to initialize backend 'cuda': FAILED_PRECONDITION: No visible GPU devices.
I0402 11:20:17.760828 22423334270784 xla_bridge.py:353] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: Interpreter Host CUDA
I0402 11:20:17.761204 22423334270784 xla_bridge.py:353] Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
I0402 11:20:17.761254 22423334270784 xla_bridge.py:353] Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
W0402 11:20:17.761305 22423334270784 xla_bridge.py:360] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
I0402 11:20:20.038884 22423334270784 run_alphafold.py:524] Have 5 models: ['model_1_pred_0', 'model_2_pred_0', 'model_3_pred_0', 'model_4_pred_0', 'model_5_pred_0']
I0402 11:20:20.039066 22423334270784 run_alphafold.py:538] Using random seed 53343 for the data pipeline
I0402 11:20:20.039302 22423334270784 run_alphafold.py:245] Predicting rhodopsin_Ischikauia.1
I0402 11:20:20.042454 22423334270784 jackhmmer.py:133] Launching subprocess "/usr/bin/jackhmmer -o /dev/null -A /var/tmp/pbs.891698.cfe/tmp6t591307/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 rhodopsin_Ischikauia.1.fasta ./uniref90/uniref90.fasta"
I0402 11:20:20.045268 22423334270784 utils.py:36] Started Jackhmmer (uniref90.fasta) query`

**Approach C.**
Lastly, if I try with both the "-r dev" and process block (i.e. with both changes A. and B.), it will run like in A. by skipping the alphafold step.

Let me know if you need more logfiles etc. and thanks again.

~Greg

**Comment by JoseEspinosa** [comment]
Hi sorry for the late reply too, 
In the message you shared with **Approach b**, I can't see any errors, only warnings, because the GPUs are not detected, but should try to run in cpus. You could check in the `.command.run` file in the directory where the process runs to see whether the `singularity.runOptions = '--nv'` is passed when running the command.
For A and C I will try to run the pipeline myself with a config as similar as possible to yours and see whether I can reproduce your issue...
